name: Demo Workflow
on: workflow_dispatch
jobs:
  print: 
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hellow Github Actions!
      - name: Print a few Lines
        run:  |
          echo It's a first Line
          echo But this is a Second Line
